//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanning
{
    [Serializable]
    public class URJointsMsg : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning/URJoints";
        public override string RosMessageName => k_RosMessageName;

        public double joint_00;
        public double joint_01;
        public double joint_02;
        public double joint_03;
        public double joint_04;
        public double joint_05;

        public URJointsMsg()
        {
            this.joint_00 = 0.0;
            this.joint_01 = 0.0;
            this.joint_02 = 0.0;
            this.joint_03 = 0.0;
            this.joint_04 = 0.0;
            this.joint_05 = 0.0;
        }

        public URJointsMsg(double joint_00, double joint_01, double joint_02, double joint_03, double joint_04, double joint_05)
        {
            this.joint_00 = joint_00;
            this.joint_01 = joint_01;
            this.joint_02 = joint_02;
            this.joint_03 = joint_03;
            this.joint_04 = joint_04;
            this.joint_05 = joint_05;
        }

        public static URJointsMsg Deserialize(MessageDeserializer deserializer) => new URJointsMsg(deserializer);

        private URJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_00);
            deserializer.Read(out this.joint_01);
            deserializer.Read(out this.joint_02);
            deserializer.Read(out this.joint_03);
            deserializer.Read(out this.joint_04);
            deserializer.Read(out this.joint_05);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_00);
            serializer.Write(this.joint_01);
            serializer.Write(this.joint_02);
            serializer.Write(this.joint_03);
            serializer.Write(this.joint_04);
            serializer.Write(this.joint_05);
        }

        public override string ToString()
        {
            return "URJointsMsg: " +
            "\njoint_00: " + joint_00.ToString() +
            "\njoint_01: " + joint_01.ToString() +
            "\njoint_02: " + joint_02.ToString() +
            "\njoint_03: " + joint_03.ToString() +
            "\njoint_04: " + joint_04.ToString() +
            "\njoint_05: " + joint_05.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
