//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanning
{
    [Serializable]
    public class ForwardKinematicsRequest : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning/ForwardKinematics";
        public override string RosMessageName => k_RosMessageName;

        public URJointsMsg target;

        public ForwardKinematicsRequest()
        {
            this.target = new URJointsMsg();
        }

        public ForwardKinematicsRequest(URJointsMsg target)
        {
            this.target = target;
        }

        public static ForwardKinematicsRequest Deserialize(MessageDeserializer deserializer) => new ForwardKinematicsRequest(deserializer);

        private ForwardKinematicsRequest(MessageDeserializer deserializer)
        {
            this.target = URJointsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "ForwardKinematicsRequest: " +
            "\ntarget: " + target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
